language: php
sudo: yes
dist: bionic

env:
  - PHPVER="7.3.14"
  - PHPVER="7.4.2"
  - PHPVER="8.0.0"
  - PHPVER="8.4.1"

# This replaces the travis supplied phpbuild which defaults to ZTS enabled
# builds.  Since we are replacing using the same config, we don't have to add
# the env stuff.
install:
  - rm -rf ~/.phpenv
  - sudo apt-get clean
  - sudo apt-get update
  - sudo apt-get purge --auto-remove mysql-client-5.7 mysql-client-core-5.7 mysql-server-5.7 mysql-server-core-5.7
  - sudo rm -rf /var/lib/mysql
  - sudo apt-get install libzip-dev libonig-dev
  - curl -L http://git.io/phpenv-installer | bash
  - travis_wait phpenv install "${PHPVER}"
  - phpenv global "${PHPVER}"
  - phpenv rehash

before_script:
  - php-config --extension-dir
  - phpize
  - ./configure
  - make
  - sed -i.stock -e 's/run-tests\.php/run-tests.php --show-diff/' Makefile

script:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1 make test

